name: .NET CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore NuGet packages
        run: nuget restore food_delivery\food_delivery.sln

      - name: Build solution
        run: msbuild food_delivery\food_delivery.sln /p:Configuration=Release

      - name: Run UT
        run: dotnet test food_delivery\food_delivery.sln --no-build --verbosity normal

