name: .NET CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore RestaurantManager\RestaurantManager.sln

      - name: Build solution
        run: msbuild RestaurantManager\RestaurantManager.sln /p:Configuration=Release

      - name: Change directory
        working-directory: ./food_delivery
        run:
          dotnet
          dotnet build --no-restore --configuration Release
          dotnet test --no-build --configuration Release --verbosity normal
