name: .NET CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Navigate to food_delivery directory
        run: cd food_delivery

      - name: Build solution
        run: msbuild food_delivery.sln /p:Configuration=Release

      - name: Run UT
        run:
          dotnet
          dotnet build --no-restore --configuration Release
          dotnet test --no-build --configuration Release --verbosity normal
